name: stampede
description: "Stampede - Unofficial mobile app for Northside High School - Stay connected with announcements, athletics, events, and school news."

publish_to: 'none' 

version: 1.0.0+12

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  sizer: ^2.0.15
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2
  
  # FIX: Replaced the non-working packages with the correct one.
  sticky_headers: ^0.3.0+2
  sliver_tools:
  figma_squircle: ^0.6.3
  url_launcher: ^6.3.1

  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  add_2_calendar: ^3.0.1
  device_calendar: ^4.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.PNG"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/flexes_icon.png
    - assets/images/grades_icon.png
    - assets/images/homecoming_bg.png
    - assets/images/hoofbeat_icon.png
    - assets/images/icon.PNG
